return {
  version = "1.2",
  luaversion = "5.1",
  tiledversion = "2020.01.22",
  orientation = "orthogonal",
  renderorder = "right-down",
  width = 32,
  height = 17,
  tilewidth = 16,
  tileheight = 16,
  nextlayerid = 17,
  nextobjectid = 12,
  properties = {},
  tilesets = {
    {
      name = "tilemap_packed",
      firstgid = 1,
      tilewidth = 16,
      tileheight = 16,
      spacing = 0,
      margin = 0,
      columns = 27,
      image = "../tileset/Tilemap/tilemap_packed.png",
      imagewidth = 432,
      imageheight = 288,
      objectalignment = "unspecified",
      tileoffset = {
        x = 0,
        y = 0
      },
      grid = {
        orientation = "orthogonal",
        width = 16,
        height = 16
      },
      properties = {},
      terrains = {},
      tilecount = 486,
      tiles = {}
    },
    {
      name = "test",
      firstgid = 487,
      tilewidth = 16,
      tileheight = 16,
      spacing = 0,
      margin = 0,
      columns = 27,
      image = "../tileset/Tilemap/test.png",
      imagewidth = 432,
      imageheight = 288,
      objectalignment = "unspecified",
      tileoffset = {
        x = 0,
        y = 0
      },
      grid = {
        orientation = "orthogonal",
        width = 16,
        height = 16
      },
      properties = {},
      terrains = {},
      tilecount = 486,
      tiles = {}
    }
  },
  layers = {
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 32,
      height = 17,
      id = 1,
      name = "grass",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eJyTZWBgkCURy6HxZcgwgxI83OyXI9GcUfupbz/DIPC/ORBboGFi7KcUw8zDBujpf0YgZkLD9E5/bFjiAB1b0tB+YuKWlul/MNmPLT2AMDOV7VeEmquEZj8uc2lZ/wy0/aS6kVL7Adv8PMo="
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 32,
      height = 17,
      id = 2,
      name = "street",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eJxjYCAPnGNkYDgPxBcYyTSAQjBq/6j9I9n+zUB7twDx1hHq/+Fs/zagmdMJ4Cs0tB/ktx1AfBYP3klj+wmZS8vwH+n2byaiXKGW/QA3vDv8"
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 32,
      height = 17,
      id = 4,
      name = "path",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eJxjYBgFgwHkDbD9rqP2j2j7ZaFuQMf0AgPt/1H7BxYMdPk3CgYGAAD6oQR7"
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 32,
      height = 17,
      id = 9,
      name = "house",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eJzbysDAsAOIt0LpnQz0BXOAeC4Snkdn+y8B8WUkfIXO9o8CwkAIiIWhWGQA7NcFYj0o1qez3a6MDAweQNoTir3obH/CANtfDbQ/GUinQHEqne0faHAY6P8jjANn/z2g3feh9h8D0scH0C2jYPgBAJXnFZo="
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 32,
      height = 17,
      id = 10,
      name = "house_details",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eJzLZWRgyAViEMhFYo8UEMAIwTKMCPYoGAWjYBSMglEwCmgLAOSXAxo="
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 32,
      height = 17,
      id = 5,
      name = "trees",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eJxjYMAE7Iy4MQcjFg1UBkqMuLEyHewfBUMHzBqg9DCbkaEBRB8YGOtB9jYMkNWjYBTQDQx0HaAAtKsOiI2gtAKdy5tkNPs8hln9BwATnwgF"
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 32,
      height = 17,
      id = 11,
      name = "extra",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eJxjYCANcDKSqIFC8A6KQfbCMD0BKyMEs0Axve1HBywDbP8oGAWjYBTQAygyQjAyeDUwThkFNAIAHW0DWA=="
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 32,
      height = 17,
      id = 6,
      name = "fruits",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eJxjYBgFgwGcYR5oF4yCkQxOYUl/o2ly5ADXAbZ/NK2NTAAADrEDgA=="
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 32,
      height = 17,
      id = 12,
      name = "benches",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eJxjYCAdaKPxBcgwgxKAbj86f7jZHwXE0VAcMwD2TwDiiVA8aQDsz2ZExfS2v40RFdPb/gBGVExv+3WBWA+K9bHYRw//zwXieXTwPw8QOxPAGjS0nxyzaGX/ayB+gwW/pZP9L4H4FRY1L+lkPycjhF4HpWMZUcVpbT8LI3Y16OK0DH9sgJrhDwDVGB9B"
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 32,
      height = 17,
      id = 3,
      name = "cars",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eJxjYCAP3GWE0P2MZBpAJbBqgOzvGWB/Lx9g+ycMsP2rB9j+UQABRwc4Hh7Qyf4uoD3dA+jXpUC7l42mebqAoVS2TRxgt66h0H4A388LEw=="
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 32,
      height = 17,
      id = 8,
      name = "player",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eJxjYBgFo2AUjIJRMApGwSigLwAACIAAAQ=="
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 13,
      name = "end",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {},
      objects = {
        {
          id = 1,
          name = "end",
          type = "",
          shape = "rectangle",
          x = 32,
          y = 32,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 15,
      name = "yellowTile",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {},
      objects = {
        {
          id = 6,
          name = "yellow1",
          type = "",
          shape = "rectangle",
          x = 32,
          y = 128,
          width = 4.8125,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 16,
      name = "blueTile",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {},
      objects = {
        {
          id = 7,
          name = "blue3",
          type = "",
          shape = "rectangle",
          x = 32,
          y = 48,
          width = 7.73913,
          height = 7.73913,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 8,
          name = "blue1",
          type = "",
          shape = "rectangle",
          x = 112,
          y = 128,
          width = 5.61364,
          height = 4.98864,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 9,
          name = "blue2",
          type = "",
          shape = "rectangle",
          x = 32,
          y = 214.813,
          width = 9.1875,
          height = 9.1875,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 14,
      name = "grass",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {},
      objects = {
        {
          id = 2,
          name = "1",
          type = "",
          shape = "rectangle",
          x = 0.5,
          y = 3,
          width = 26.5,
          height = 266.5,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 3,
          name = "2",
          type = "",
          shape = "rectangle",
          x = 53,
          y = -0.5,
          width = 234.5,
          height = 122.5,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 4,
          name = "3",
          type = "",
          shape = "rectangle",
          x = 52,
          y = 149,
          width = 235,
          height = 122,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 5,
          name = "",
          type = "",
          shape = "rectangle",
          x = 0.5,
          y = 227.5,
          width = 254,
          height = 43.5,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 10,
          name = "4",
          type = "",
          shape = "rectangle",
          x = 128,
          y = 0,
          width = 160,
          height = 256,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    }
  }
}
