return {
  version = "1.2",
  luaversion = "5.1",
  tiledversion = "2020.01.22",
  orientation = "orthogonal",
  renderorder = "right-down",
  width = 30,
  height = 15,
  tilewidth = 16,
  tileheight = 16,
  nextlayerid = 6,
  nextobjectid = 1,
  properties = {},
  tilesets = {
    {
      name = "tilemap",
      firstgid = 1,
      tilewidth = 16,
      tileheight = 16,
      spacing = 0,
      margin = 0,
      columns = 28,
      image = "../tileset/Tilemap/tilemap.png",
      imagewidth = 458,
      imageheight = 305,
      objectalignment = "unspecified",
      tileoffset = {
        x = 0,
        y = 0
      },
      grid = {
        orientation = "orthogonal",
        width = 16,
        height = 16
      },
      properties = {},
      terrains = {},
      tilecount = 532,
      tiles = {}
    },
    {
      name = "tilemap_packed",
      firstgid = 533,
      tilewidth = 16,
      tileheight = 16,
      spacing = 0,
      margin = 0,
      columns = 27,
      image = "../tileset/Tilemap/tilemap_packed.png",
      imagewidth = 432,
      imageheight = 288,
      objectalignment = "unspecified",
      tileoffset = {
        x = 0,
        y = 0
      },
      grid = {
        orientation = "orthogonal",
        width = 16,
        height = 16
      },
      properties = {},
      terrains = {},
      tilecount = 486,
      tiles = {}
    }
  },
  layers = {
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 30,
      height = 15,
      id = 1,
      name = "grass",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eJwzZGJgMBzFo3gUj+JRPIpHKAYA9N1Zpw=="
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 30,
      height = 15,
      id = 2,
      name = "path",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eJxjYGZgYBgALD3CsNkA4cEGIplG7R21d9TeoWrvcAUAyzcQ6Q=="
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 30,
      height = 15,
      id = 3,
      name = "house",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eJxjYBgcII+JgSEfCRcw0cdeVaA9S5GwKp3sdQDao46EHehkbxnQngokXEYne0fBKBgFo2CwAgBgowfW"
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 30,
      height = 15,
      id = 4,
      name = "house_details",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eJxjYBgFAwHSmRkY6pkhbBCdzkwfe+cC7ZkFxIZQei6d7B0Fo2AUjILBCgDL5gSH"
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 30,
      height = 15,
      id = 5,
      name = "path_details",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eJxjYBh8IIl5oF0wvIElMyo9CkbBKBgFIxkAAPJ/AN4="
    }
  }
}
