return {
  version = "1.2",
  luaversion = "5.1",
  tiledversion = "2020.01.22",
  orientation = "orthogonal",
  renderorder = "right-down",
  width = 32,
  height = 17,
  tilewidth = 16,
  tileheight = 16,
  nextlayerid = 18,
  nextobjectid = 26,
  properties = {},
  tilesets = {
    {
      name = "tilemap_packed",
      firstgid = 1,
      tilewidth = 16,
      tileheight = 16,
      spacing = 0,
      margin = 0,
      columns = 27,
      image = "../tileset/Tilemap/tilemap_packed.png",
      imagewidth = 432,
      imageheight = 288,
      objectalignment = "unspecified",
      tileoffset = {
        x = 0,
        y = 0
      },
      grid = {
        orientation = "orthogonal",
        width = 16,
        height = 16
      },
      properties = {},
      terrains = {},
      tilecount = 486,
      tiles = {}
    },
    {
      name = "new",
      firstgid = 487,
      tilewidth = 16,
      tileheight = 16,
      spacing = 0,
      margin = 0,
      columns = 4,
      image = "../tileset/new.png",
      imagewidth = 64,
      imageheight = 32,
      objectalignment = "unspecified",
      tileoffset = {
        x = 0,
        y = 0
      },
      grid = {
        orientation = "orthogonal",
        width = 16,
        height = 16
      },
      properties = {},
      terrains = {},
      tilecount = 8,
      tiles = {}
    },
    {
      name = "test",
      firstgid = 495,
      tilewidth = 16,
      tileheight = 16,
      spacing = 0,
      margin = 0,
      columns = 27,
      image = "../tileset/Tilemap/test.png",
      imagewidth = 432,
      imageheight = 288,
      objectalignment = "unspecified",
      tileoffset = {
        x = 0,
        y = 0
      },
      grid = {
        orientation = "orthogonal",
        width = 16,
        height = 16
      },
      properties = {},
      terrains = {},
      tilecount = 486,
      tiles = {}
    }
  },
  layers = {
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 32,
      height = 17,
      id = 5,
      name = "background",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eJxjYBgFtAB5UDxQdtMKcDMRtjsPiT0QdtMi7Ae73chuGM52g8SQxZHtpKb9hPyNbCe1w4AYu9HVoKc/ct1BrL+xAUrDghK7cbmBnnZjcwO97UZ2w0DZTQoAAKmdEm8="
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 32,
      height = 17,
      id = 1,
      name = "water",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eJw7zsDAcHwUUxVvgNIbaWT+VqaB8xvI7oGyf9Ru2mFrxoH1dxgW++llN8jv6PbTM74H0u6BCvNRuzHtHgj7B9LfIAwA0gOinQ=="
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 32,
      height = 17,
      id = 2,
      name = "land",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eJxjYBgFQxnsYkTggbJ3MNg/ajf97R8IMJjsH+jwH8nhMBjcMFD2RwFxNBIuQ+ODcAwN7S+F2okPlxNpFgBmWSqb"
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 32,
      height = 17,
      id = 3,
      name = "path",
      visible = true,
      opacity = 1,
      offsetx = -80,
      offsety = 0,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eJxjYBgFwxG4ArEx08DZ7TowVo/aPYD2DyQYDPaPumHUDchuGAWEAQCjfAWa"
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 32,
      height = 17,
      id = 4,
      name = "different_path",
      visible = true,
      opacity = 1,
      offsetx = -80,
      offsety = 0,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eJxjYBgFo2AUjALywSXmkW3/KBgFo4A8AACqLAGr"
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 32,
      height = 17,
      id = 7,
      name = "park",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eJztzbENgDAMBdEjbWZwCyuw/0wZACiQCAQwErYp+NI1lqUngPypKx2M1PUJcqpvwvGv1VN7mJ03F2lrfStb41vad761feV72Ge+l93yPe29721v/Qh79aNsgu1lkfYXNgH5mCJv"
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 32,
      height = 17,
      id = 8,
      name = "park_details",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eJxjYBgF+IAkI3n6LKjrDKxgAxA/RuJvYaKDpTjsngm0exed7Ee3ezUQn6GP1SPWbhA4MYB2o9v/EIg30tn+00C8dtQNg9INx+hsP7obBsL+4QAAn88g1w=="
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 32,
      height = 17,
      id = 9,
      name = "trees",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eJxjYMAEGsyYYs5YxHCJE6MfWQ26elx2EQuI0Y+shlj7sPmLnoDScMEGcPmJXn4lJV3RAwzHOCYGjFR/j4KBBaPpbmQDAAEZBT0="
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 32,
      height = 17,
      id = 10,
      name = "people",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {},
      encoding = "base64",
      compression = "zlib",
      data = "eJxjYCAdzCdDDzngKp3sGQUQsI5xoF0wCugNpAfaAaNgFAwDsILO9vWjldWHgfgoVGwiHcrxVVjseAAVW0OC/QDWigfL"
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 14,
      name = "water",
      visible = false,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {},
      objects = {
        {
          id = 1,
          name = "1",
          type = "",
          shape = "rectangle",
          x = 304.667,
          y = 48,
          width = 63.3333,
          height = 192,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 2,
          name = "2",
          type = "",
          shape = "rectangle",
          x = 272,
          y = 80,
          width = 95,
          height = 128,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 3,
          name = "3",
          type = "",
          shape = "rectangle",
          x = 256,
          y = 96,
          width = 112,
          height = 96,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 7,
          name = "4",
          type = "",
          shape = "rectangle",
          x = 240,
          y = 112,
          width = 129,
          height = 64,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 8,
          name = "5",
          type = "",
          shape = "rectangle",
          x = 224,
          y = 128,
          width = 144,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 9,
          name = "6",
          type = "",
          shape = "rectangle",
          x = 252.364,
          y = 48,
          width = 16.9091,
          height = 12.3636,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 10,
          name = "7",
          type = "",
          shape = "rectangle",
          x = 235.273,
          y = 48,
          width = 17.0909,
          height = 28.3636,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 11,
          name = "8",
          type = "",
          shape = "rectangle",
          x = 220.727,
          y = 48,
          width = 15.2727,
          height = 44.1818,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 12,
          name = "9",
          type = "",
          shape = "rectangle",
          x = 203.818,
          y = 48,
          width = 16.5455,
          height = 58.9091,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 13,
          name = "10",
          type = "",
          shape = "rectangle",
          x = 192,
          y = 64,
          width = 12,
          height = 59.0909,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 14,
          name = "11",
          type = "",
          shape = "rectangle",
          x = 176,
          y = 80,
          width = 16,
          height = 144,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 15,
          name = "12",
          type = "",
          shape = "rectangle",
          x = 175.667,
          y = 160,
          width = 32.3333,
          height = 80,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 16,
          name = "13",
          type = "",
          shape = "rectangle",
          x = 192.333,
          y = 176,
          width = 31.6667,
          height = 64,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 17,
          name = "14",
          type = "",
          shape = "rectangle",
          x = 191.333,
          y = 192,
          width = 48.6667,
          height = 48,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 18,
          name = "15",
          type = "",
          shape = "rectangle",
          x = 192.333,
          y = 208,
          width = 63.6667,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 19,
          name = "16",
          type = "",
          shape = "rectangle",
          x = 192,
          y = 224,
          width = 80,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 20,
          name = "17",
          type = "",
          shape = "rectangle",
          x = 208,
          y = 240,
          width = 160,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 25,
          name = "18",
          type = "",
          shape = "rectangle",
          x = 288,
          y = 64,
          width = 67.4359,
          height = 175.333,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 15,
      name = "end",
      visible = false,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {},
      objects = {
        {
          id = 21,
          name = "end",
          type = "",
          shape = "rectangle",
          x = 288,
          y = 32,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 16,
      name = "player",
      visible = false,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {},
      objects = {
        {
          id = 22,
          name = "player",
          type = "",
          shape = "rectangle",
          x = 272,
          y = 224,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 17,
      name = "yellow",
      visible = false,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      properties = {},
      objects = {
        {
          id = 24,
          name = "yellow",
          type = "",
          shape = "rectangle",
          x = 192,
          y = 128,
          width = 16,
          height = 32,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    }
  }
}
